name: gas_bank_operator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  shared_preferences: 2.1.0
  flutter_launcher_icons: 0.13.0
  intl: 0.18.0
  fluttertoast: 8.2.1
  curved_navigation_bar: 1.0.3
  persistent_bottom_nav_bar: 5.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

#flutter_icons:
#  android: launcher_icon
#  image_path: assets/images/gas_bank.jpg
#  ios: true
#  min_sdk_android: 21

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

